/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.raven.form;

import com.raven.Model2.VCmodel;
import com.raven.Service.Service_Voucher;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class ChiTietVoucher extends javax.swing.JDialog {

    public enum ActionType {
        ADD, EDIT
    }
    private ActionType actionType;
    private Service_Voucher sv = new Service_Voucher();
    private List<VCmodel> list = sv.getAll();

    /**
     * Creates new form ChiTietVoucher
     */
    public ChiTietVoucher(java.awt.Frame parent, boolean modal, ActionType actionType) {
        super(parent, modal);
        initComponents();
        this.actionType = actionType;
        this.setLocationRelativeTo(null);
        if (actionType == ActionType.EDIT) {
            lbName.setText("Sửa mã giảm giá");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtma = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        luuBtn = new javax.swing.JButton();
        txtTen = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ngaybd = new com.toedter.calendar.JDateChooser();
        giobd = new javax.swing.JComboBox<>();
        phutbd = new javax.swing.JComboBox<>();
        phutkt = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        ngaykt = new com.toedter.calendar.JDateChooser();
        giokt = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtTien = new javax.swing.JTextField();
        lbName = new javax.swing.JLabel();

        txtma.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        luuBtn.setBackground(new java.awt.Color(18, 64, 118));
        luuBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        luuBtn.setForeground(new java.awt.Color(249, 232, 151));
        luuBtn.setText("Lưu");
        luuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Tên mã giảm giá");

        jLabel2.setText("Ngày bắt đầu");

        giobd.setEditable(true);
        giobd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        phutbd.setEditable(true);
        phutbd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        phutkt.setEditable(true);
        phutkt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        phutkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phutktActionPerformed(evt);
            }
        });

        jLabel3.setText("Ngày kết thúc");

        giokt.setEditable(true);
        giokt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        jLabel4.setText("Số tiền giảm");

        lbName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbName.setText("Thêm mới mã giảm giá");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(luuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtTen)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(ngaybd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(giobd, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(phutbd, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(ngaykt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(giokt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(phutkt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtTien, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(44, 44, 44)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(ngaybd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(giobd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phutbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(ngaykt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(giokt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phutkt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(luuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phutktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phutktActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phutktActionPerformed

    public boolean checkNull() {
        if (txtTen.getText() == null || txtTen.getText().trim().isEmpty()
                || ngaybd.getDate() == null || ngaykt.getDate() == null
                || txtTien.getText() == null || txtTien.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
            return false;
        }
        String tienText = txtTien.getText().trim();
        if (txtTien.getText().startsWith("0") || !tienText.matches("\\d+(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số");
            return false;
        }
        return true;
    }

    private void luuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuBtnActionPerformed
        // TODO add your handling code here:
        if (actionType == ActionType.ADD) {
            // Xử lý khi thêm mới
            if (!checkNull()) {
                return;
            }
            Integer ma = 0;
            String ten = txtTen.getText();
            String gbd = " " + giobd.getSelectedItem().toString() + ":" + phutbd.getSelectedItem().toString() + ":00";
            String gkt = " " + giokt.getSelectedItem().toString() + ":" + phutkt.getSelectedItem().toString() + ":00";
            Date nbd = ngaybd.getDate();
            Date nkt = ngaykt.getDate();
            String money = txtTien.getText();
            String status = "Chưa diễn ra";

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String ngaybatdau = sdf.format(nbd);
            String ngayketthuc = sdf.format(nkt);

            VCmodel vc = new VCmodel(ma, ten, ngaybatdau + gbd, ngayketthuc + gkt, money, status);
            boolean addVC = sv.add(vc);

            if (addVC) {
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }
        } else if (actionType == ActionType.EDIT) {
            // Xử lý khi sửa
            if (!checkNull()) {
                return;
            }
            Integer ma = Integer.valueOf(txtma.getText());
            String ten = txtTen.getText();
            String gbd = " " + giobd.getSelectedItem().toString() + ":" + phutbd.getSelectedItem().toString() + ":00";
            String gkt = " " + giokt.getSelectedItem().toString() + ":" + phutkt.getSelectedItem().toString() + ":00";
            Date nbd = ngaybd.getDate();
            Date nkt = ngaykt.getDate();
            String money = txtTien.getText();
            String status = "Chưa diễn ra";

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String ngaybatdau = sdf.format(nbd);
            String ngayketthuc = sdf.format(nkt);

            VCmodel vc = new VCmodel(ma, ten, ngaybatdau + gbd, ngayketthuc + gkt, money, status);
            boolean updateVC = sv.update(vc);

            if (updateVC) {
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Sửa thất bại");
            }
        }
    }//GEN-LAST:event_luuBtnActionPerformed

    public void delete() {
        Integer ma = Integer.valueOf(txtma.getText());
        String ten = txtTen.getText();
        String gbd = " " + giobd.getSelectedItem().toString() + ":" + phutbd.getSelectedItem().toString() + ":00";
        String gkt = " " + giokt.getSelectedItem().toString() + ":" + phutkt.getSelectedItem().toString() + ":00";
        Date nbd = ngaybd.getDate();
        Date nkt = ngaykt.getDate();
        String money = txtTien.getText();
        String status = "Đã xóa";

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String ngaybatdau = sdf.format(nbd);
        String ngayketthuc = sdf.format(nkt);

        VCmodel vc = new VCmodel(ma, ten, ngaybatdau + gbd, ngayketthuc + gkt, money, status);
        boolean deleteVC = sv.delete(vc);

        if (deleteVC) {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
    }

    public void detail(int index) {
        try {
            VCmodel vch = list.get(index);
            txtma.setText(String.valueOf(vch.getMa()));
            txtTen.setText(vch.getTen());
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            Date datebd = format.parse(vch.getNgay_bd());
            Date datekt = format.parse(vch.getNgay_kt());
            ngaybd.setDate(datebd);
            ngaykt.setDate(datekt);

            Calendar calendar_bd = Calendar.getInstance();
            Calendar calendar_kt = Calendar.getInstance();
            calendar_bd.setTime(datebd);
            calendar_kt.setTime(datekt);
            // Lấy giờ từ đối tượng Calendar
            int hourOfDay_bd = calendar_bd.get(Calendar.HOUR_OF_DAY); // Lấy giờ trong 24 giờ
            int minuteOfDay_bd = calendar_bd.get(Calendar.MINUTE);

            int hourOfDay_kt = calendar_kt.get(Calendar.HOUR_OF_DAY); // Lấy giờ trong 24 giờ
            int minuteOfDay_kt = calendar_kt.get(Calendar.MINUTE);

            giobd.setSelectedItem(hourOfDay_bd);
            phutbd.setSelectedItem(minuteOfDay_bd);

            giokt.setSelectedItem(hourOfDay_kt);
            phutkt.setSelectedItem(minuteOfDay_kt);

//            System.out.println(hourOfDay_bd);
//            System.out.println(minuteOfDay_bd);
            txtTien.setText(vch.getTien_giam());
        } catch (ParseException ex) {
            Logger.getLogger(ChiTietVoucher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChiTietVoucher dialog = new ChiTietVoucher(new javax.swing.JFrame(), true, ActionType.ADD);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> giobd;
    private javax.swing.JComboBox<String> giokt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbName;
    private javax.swing.JButton luuBtn;
    private com.toedter.calendar.JDateChooser ngaybd;
    private com.toedter.calendar.JDateChooser ngaykt;
    private javax.swing.JComboBox<String> phutbd;
    private javax.swing.JComboBox<String> phutkt;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTien;
    private javax.swing.JTextField txtma;
    // End of variables declaration//GEN-END:variables
}
