/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.raven.form;

import com.raven.Model2.khachHang;
import com.raven.Service.HoaDonRepository;
import com.raven.Service.InterfaceHoaDonRepo;
import com.raven.Service.khachHang_Service;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultButtonModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gosgu
 */
public class KhachHang_Button extends javax.swing.JDialog {

    private khachHang_Service service = new khachHang_Service();
    InterfaceHoaDonRepo svHD = new HoaDonRepository();
    DefaultTableModel model = new DefaultTableModel();
    private List<khachHang> lst = new ArrayList<>();
    
    
    public KhachHang_Button(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        lst = service.getAll_KH();
        loadKhachHang(lst);
    }
    
    private void loadKhachHang(List<khachHang> lst){
        model = (DefaultTableModel) tblKH.getModel();
        model.setRowCount(0);
        lst.forEach(s -> {
            String gioiTinh = "";
            if (s.getGioi_tinh() == 0) {
                gioiTinh = "Nam";
            } else if (s.getGioi_tinh() == 1) {
                gioiTinh = "Nữ";
            }
            model.addRow(new Object[]{
                s.getId(),
                s.getTen_khach(),
                gioiTinh,
                s.getSdt(),
                s.getNgay_them(),
                s.getTrang_thai()
            });
        });
    }
    
    private khachHang getQLKhachHang(){
        String id = null;
        String ten = null;
        String sdt = null;
        
        khachHang kh = new khachHang(id, ten, sdt);
        return kh;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKH = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Tên", "Giới Tính", "SĐT", "Ngày Thêm", "Trạng Thái"
            }
        ));
        tblKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblKHMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblKH);
        if (tblKH.getColumnModel().getColumnCount() > 0) {
            tblKH.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblKHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKHMousePressed
        if(evt.getClickCount() == 2){
            int row = this.tblKH.getSelectedRow();
            if(row < 0){
                JOptionPane.showMessageDialog(this, "Vui lòng chọn khách hàng @");
                return;
            }
            khachHang kh = this.lst.get(row);
            this.ThemKhachHang(kh.getId());
        }
    }//GEN-LAST:event_tblKHMousePressed

    
    private void ThemKhachHang(String IdKhachHang){
        int row = this.tblKH.getSelectedRow();
        String tenKH = this.lst.get(row).getTen_khach();
        String sdt = this.lst.get(row).getSdt();
        khachHang kh = this.getQLKhachHang();
        kh.setTen_khach(tenKH);
        kh.setSdt(sdt);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachHang_Button.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachHang_Button.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachHang_Button.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachHang_Button.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KhachHang_Button dialog = new KhachHang_Button(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKH;
    // End of variables declaration//GEN-END:variables
}
