/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.raven.form;

import com.raven.Model2.NXB;
import com.raven.Model2.Sach;
import com.raven.Model2.TacGia;
import com.raven.Model2.TheLoai;
import com.raven.Service.SachService;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class Sach_Dialog extends javax.swing.JDialog {

    private final SachService sv = new SachService();
    private List<TacGia> listTG = sv.getAllTG();
    private List<TheLoai> listTL = sv.getAllTL();
    private List<NXB> listNXB = sv.getAllNXB();
    private List<Sach> list = sv.getAll();

    public enum ActionType {
        ADD, EDIT
    }
    private Map<String, Integer> nxbMap = new HashMap<>();
    private ActionType actionType;

    /**
     * Creates new form Sach_Dialog
     */
    public Sach_Dialog(java.awt.Frame parent, boolean modal, ActionType actionType) {
        super(parent, modal);
        initComponents();
        addNXBToComboBox(listNXB);
        addTGToComboBox(listTG);
        addTLToComboBox(listTL);
        this.actionType = actionType;
        this.setLocationRelativeTo(null);
        if (actionType == ActionType.EDIT) {
            lblName.setText("Sửa thông tin sách");
        }
    }

    public int getSelectedNXBId(String nxbTen) {
        return nxbMap.get(nxbTen); // Trả về ID của nhà xuất bản từ tên
    }

    public int getSelectedTGId(String TGTen) {
        return nxbMap.get(TGTen); // Trả về ID của nhà xuất bản từ tên
    }

    public int getSelectedTLId(String TLTen) {
        return nxbMap.get(TLTen); // Trả về ID của nhà xuất bản từ tên
    }

    public void addNXBToComboBox(List<NXB> list) {
        for (NXB nxb : list) {
            cbxNXB.addItem(nxb.getTen());
            nxbMap.put(nxb.getTen(), nxb.getId());
        }
    }

    public void addTGToComboBox(List<TacGia> list) {
        for (TacGia nxb : list) {
            cbxTG.addItem(nxb.getTen());
            nxbMap.put(nxb.getTen(), Integer.valueOf(nxb.getId()));
        }
    }

    public void addTLToComboBox(List<TheLoai> list) {
        for (TheLoai nxb : list) {
            cbxTL.addItem(nxb.getTen());
            nxbMap.put(nxb.getTen(), Integer.valueOf(nxb.getId()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMa = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTenSach = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSoTrang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbxTG = new javax.swing.JComboBox<>();
        cbxTL = new javax.swing.JComboBox<>();
        cbxNXB = new javax.swing.JComboBox<>();
        txtGia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        luuBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblHinhAnh = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rdo1 = new javax.swing.JRadioButton();
        rdo2 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        txtNgayThem = new javax.swing.JTextField();

        txtMa.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Thêm mới sách");

        jLabel2.setText("Tên sách");

        jLabel3.setText("Số trang");

        jLabel4.setText("Giá bán");

        jLabel5.setText("Nhà xuất bản");

        jLabel6.setText("Tác giả");

        jLabel7.setText("Thể loại");

        jLabel8.setText("Mô tả");

        cbxTG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   " }));

        cbxTL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   " }));

        cbxNXB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  " }));
        cbxNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNXBActionPerformed(evt);
            }
        });

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane1.setViewportView(txtMoTa);

        luuBtn.setText("Lưu");
        luuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("Hình ảnh");

        lblHinhAnh.setText("jLabel10");
        lblHinhAnh.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblHinhAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhAnhMouseClicked(evt);
            }
        });

        jLabel1.setText("Trạng thái");

        buttonGroup1.add(rdo1);
        rdo1.setSelected(true);
        rdo1.setText("Hiện");

        buttonGroup1.add(rdo2);
        rdo2.setText("Ẩn");
        rdo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Ngày thêm");

        txtNgayThem.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenSach, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(txtGia)
                            .addComponent(txtSoTrang)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(rdo1)
                                .addGap(40, 40, 40)
                                .addComponent(rdo2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(luuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxNXB, javax.swing.GroupLayout.Alignment.LEADING, 0, 348, Short.MAX_VALUE)
                            .addComponent(cbxTL, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxTG, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNgayThem, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbxTG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(cbxNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSoTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(cbxTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(rdo1)
                            .addComponent(rdo2)
                            .addComponent(jLabel10)
                            .addComponent(txtNgayThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(luuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void luuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuBtnActionPerformed
        // TODO add your handling code here:
        if (actionType == ActionType.ADD) {
            add();
        } else if (actionType == ActionType.EDIT) {
            update();
        }
    }//GEN-LAST:event_luuBtnActionPerformed

    private void cbxNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNXBActionPerformed

    private void rdo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo2ActionPerformed

    private void lblHinhAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhAnhMouseClicked
        // TODO add your handling code here:
        openFileChooser();
    }//GEN-LAST:event_lblHinhAnhMouseClicked

    private void add() {
        String ma = "";
        String ten = txtTenSach.getText();
        String sotrang = txtSoTrang.getText();
        String gia = txtGia.getText();
        String sl = "";
        String ngaythem = "";
        String selectedNXB = (String) cbxNXB.getSelectedItem();
        String nhaxb = String.valueOf(nxbMap.get(selectedNXB));
        String selectedTG = (String) cbxTG.getSelectedItem();
        String tgia = String.valueOf(nxbMap.get(selectedTG));
        String selectedTL = (String) cbxTL.getSelectedItem();
        String tloai = String.valueOf(nxbMap.get(selectedTL));
        String hinhAnh = lblHinhAnh.getText();
        String mta = txtMoTa.getText();
        String tthai = "";
        if (rdo1.isSelected()) {
            tthai = "Hiện";
        } else if (rdo2.isSelected()) {
            tthai = "Ẩn";
        }

        Sach sh = new Sach(ma, ten, sotrang, gia, sl, ngaythem, nhaxb, tgia, tloai, hinhAnh, mta, tthai);
        boolean addS = sv.add(sh);
        if (addS) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
        }
    }

    private void update() {
        String ma = "";
        String ten = txtTenSach.getText();
        String sotrang = txtSoTrang.getText();
        String gia = txtGia.getText();
        String sl = "";
        String ngaythem = "";
        String selectedNXB = (String) cbxNXB.getSelectedItem();
        String nhaxb = String.valueOf(nxbMap.get(selectedNXB));
        String selectedTG = (String) cbxTG.getSelectedItem();
        String tgia = String.valueOf(nxbMap.get(selectedTG));
        String selectedTL = (String) cbxTL.getSelectedItem();
        String tloai = String.valueOf(nxbMap.get(selectedTL));
        String hinhAnh = lblHinhAnh.getText();
        String mta = txtMoTa.getText();
        String tthai = "";
        if (rdo1.isSelected()) {
            tthai = "Hiện";
        } else if (rdo2.isSelected()) {
            tthai = "Ẩn";
        }

        Sach sh = new Sach(ma, ten, sotrang, gia, sl, ngaythem, nhaxb, tgia, tloai, hinhAnh, mta, tthai);
        boolean addS = sv.update(sh);
        if (addS) {
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Sửa thất bại");
        }
    }

    public void detail(int index) {
        Sach s = list.get(index);
        txtTenSach.setText(s.getTenSach());
        txtSoTrang.setText(s.getSoTrang());
        txtGia.setText(s.getGiaBan());
        cbxNXB.setSelectedItem(s.getNxb());
        cbxTG.setSelectedItem(s.getTacGia());
        cbxTL.setSelectedItem(s.getTheLoai());
        lblHinhAnh.setText(s.getHinhAnh());
        loadImageFromComputer(s.getHinhAnh());
        txtMoTa.setText(s.getMoTa());
        if ("Hiện".equals(s.getTrangThai())) {
            rdo1.setSelected(true);
        } else if (s.getTrangThai().equals("Ẩn")) {
            rdo2.setSelected(true);
        }
        txtNgayThem.setText(s.getNgayThem());

    }

    public void delete() {
        String ma = "";
        String ten = txtTenSach.getText();
        String sotrang = txtSoTrang.getText();
        String gia = txtGia.getText();
        String sl = "";
        String ngaythem = "";
        String selectedNXB = (String) cbxNXB.getSelectedItem();
        String nhaxb = String.valueOf(nxbMap.get(selectedNXB));
        String selectedTG = (String) cbxTG.getSelectedItem();
        String tgia = String.valueOf(nxbMap.get(selectedTG));
        String selectedTL = (String) cbxTL.getSelectedItem();
        String tloai = String.valueOf(nxbMap.get(selectedTL));
        String hinhAnh = lblHinhAnh.getText();
        String mta = txtMoTa.getText();
        String tthai = "";
        if (rdo1.isSelected()) {
            tthai = "Hiện";
        } else if (rdo2.isSelected()) {
            tthai = "Ẩn";
        }

        Sach sh = new Sach(ma, ten, sotrang, gia, sl, ngaythem, nhaxb, tgia, tloai, hinhAnh, mta, tthai);
        boolean addS = sv.delete(sh);
        if (addS) {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
    }

    public boolean checkNull() {
        return true;
    }

    private void openFileChooser() {
        JFileChooser fileChooser = new JFileChooser();

        // Show the file chooser dialog
        int result = fileChooser.showOpenDialog(this);

        // Check if a file was selected
        if (result == JFileChooser.APPROVE_OPTION) {
            // Get the selected file
            File selectedFile = fileChooser.getSelectedFile();

            // Set the image label to display the selected image
            lblHinhAnh.setText(selectedFile.getAbsolutePath());
        }
    }

    private void loadImageFromComputer(String imageName) {
        try {
            // Lấy đường dẫn đầy đủ của ảnh từ tên ảnh và thư mục lưu trữ
            String imagePath = "" + File.separator + imageName;

            // Đọc dữ liệu ảnh từ file
            File imageFile = new File(imagePath);
            byte[] imageData = new byte[(int) imageFile.length()];
            FileInputStream fis = new FileInputStream(imageFile);
            fis.read(imageData);
            fis.close();

            // Chuyển đổi dữ liệu ảnh thành đối tượng hình ảnh
            ImageIcon imageIcon = new ImageIcon(imageData);
            Image image = imageIcon.getImage();
            Image scaledImage = image.getScaledInstance(lblHinhAnh.getWidth(), lblHinhAnh.getHeight(), Image.SCALE_SMOOTH);

            // Đặt ảnh vào JLabel
            lblHinhAnh.setIcon(new ImageIcon(scaledImage));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sach_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sach_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sach_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sach_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sach_Dialog dialog = new Sach_Dialog(new javax.swing.JFrame(), true, ActionType.ADD);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxNXB;
    private javax.swing.JComboBox<String> cbxTG;
    private javax.swing.JComboBox<String> cbxTL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JLabel lblName;
    private javax.swing.JButton luuBtn;
    private javax.swing.JRadioButton rdo1;
    private javax.swing.JRadioButton rdo2;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtNgayThem;
    private javax.swing.JTextField txtSoTrang;
    private javax.swing.JTextField txtTenSach;
    // End of variables declaration//GEN-END:variables
}
