SELECT * FROM Sach;
SELECT * FROM TheLoai;
SELECT * FROM TacGia;
SELECT * FROM NhaXuatBan;
SELECT * FROM KhachHang;
SELECT * FROM NhanVien;
SELECT * FROM Voucher;
SELECT * FROM KhuyenMai;
SELECT * FROM ChiTietSach;
SELECT * FROM ChiTietKhuyenMai;
SELECT * FROM HoaDon;
SELECT * FROM ChiTietHoaDon;




EXEC sp_msforeachtable 'ALTER TABLE ? NOCHECK CONSTRAINT ALL';
DELETE FROM Sach;
DELETE FROM TheLoai;
DELETE FROM TacGia;
DELETE FROM NhaXuatBan;
DELETE FROM KhachHang;
DELETE FROM NhanVien;
DELETE FROM Voucher;
DELETE FROM KhuyenMai;
DELETE FROM ChiTietSach;
DELETE FROM ChiTietKhuyenMai;
DELETE FROM HoaDon;
DELETE FROM ChiTietHoaDon;

DBCC CHECKIDENT ('Sach', RESEED, 0);
DBCC CHECKIDENT ('TheLoai', RESEED, 0);
DBCC CHECKIDENT ('TacGia', RESEED, 0);
DBCC CHECKIDENT ('NhaXuatBan', RESEED, 0);
DBCC CHECKIDENT ('KhachHang', RESEED, 0);
DBCC CHECKIDENT ('NhanVien', RESEED, 0);
DBCC CHECKIDENT ('Voucher', RESEED, 0);
DBCC CHECKIDENT ('KhuyenMai', RESEED, 0);
DBCC CHECKIDENT ('ChiTietSach', RESEED, 0);
DBCC CHECKIDENT ('ChiTietKhuyenMai', RESEED, 0);
DBCC CHECKIDENT ('HoaDon', RESEED, 0);
DBCC CHECKIDENT ('ChiTietHoaDon', RESEED, 0);
EXEC sp_msforeachtable 'ALTER TABLE ? WITH CHECK CHECK CONSTRAINT ALL';